# 1.Write a NumPy program to test whether none of the elements of a given array is zero


In [1]:
import numpy as np
x = np.array([1, 2, 3, 4])
print("Original array:")
print(x)
print("Test if none of the elements of the said array is zero:")
print(np.all(x))




Original array:
[1 2 3 4]
Test if none of the elements of the said array is zero:
True


# 2.Write a NumPy program to test whether any of the elements of a given array is non-zero

In [2]:
import numpy as np
x = np.array([1, 0, 0, 0])
print("Original array:")
print(x)
print("Test whether any of the elements of a given array is non-zero:")
print(np.any(x))


Original array:
[1 0 0 0]
Test whether any of the elements of a given array is non-zero:
True


# 3.Create an identity matrix of dimension 4-by-4
Eg:
[[1. 0. 0. 0.]
[0. 1. 0. 0.]
[0. 0. 1. 0.]
[0. 0. 0. 1.]]

In [3]:
import numpy as np
 
a = np.identity(4, dtype = float)
print("Matrix b : \n", a)

Matrix b : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# 4.Convert a 1-D array to a 3-D array

In [4]:
import numpy as np
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
newarr = arr.reshape(2, 3, 2)
print(newarr)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


# 5.Convert all the elements of a numpy array from float to integer datatype

In [5]:
import numpy as np
x= np.array([[12.0, 12.51], [2.34, 7.98], [25.23, 36.50]])
print("Original array elements:")
print(x)
print("Convert float values to integer values:")
print(x.astype(int))


Original array elements:
[[12.   12.51]
 [ 2.34  7.98]
 [25.23 36.5 ]]
Convert float values to integer values:
[[12 12]
 [ 2  7]
 [25 36]]


# 6.Create a 10x10 array with random values and find the minimum and maximum values

In [6]:
import numpy as np
x = np.random.random((10,10))
print("Original Array:")
print(x) 
xmin, xmax = x.min(), x.max()
print("Minimum and Maximum Values:")
print(xmin, xmax)


Original Array:
[[0.76270566 0.15361051 0.52171714 0.30473792 0.49966337 0.2846075
  0.51307609 0.64414401 0.87531148 0.55338131]
 [0.09836208 0.26119506 0.68934876 0.49454072 0.53762371 0.20267855
  0.20618492 0.0879576  0.07851692 0.32259407]
 [0.46152947 0.76282026 0.80768662 0.59708386 0.49234109 0.61595417
  0.18343121 0.14241359 0.74418108 0.74525494]
 [0.14957419 0.75301896 0.55739564 0.99569005 0.15571462 0.21924944
  0.28199115 0.83661549 0.53451809 0.4645884 ]
 [0.97891396 0.0442682  0.35978705 0.07764127 0.82262413 0.37643871
  0.45697772 0.96643577 0.75750986 0.45477332]
 [0.6027719  0.06804662 0.34756372 0.12002521 0.62649928 0.26042857
  0.15596518 0.50580947 0.89745755 0.98215748]
 [0.05529245 0.00180549 0.22098911 0.62913772 0.04851514 0.37078431
  0.41092567 0.12706277 0.09937838 0.23644625]
 [0.70279513 0.82167175 0.34920398 0.28760809 0.60308813 0.50903625
  0.92011863 0.83687571 0.75113352 0.02066258]
 [0.67492025 0.74451427 0.73686705 0.4165324  0.13318039 0.677471

# 7.Create a random vector of size 30 and find the mean value

In [7]:
import numpy as np
x = np.random.random(30)
m = x.mean()
print(m)


0.48669262725828594


# 8.Create a 2d array with 1 on the border and 0 inside

In [8]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("1 on the border and 0 inside in the array")
x[1:-1,1:-1] = 0
print(x)


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
1 on the border and 0 inside in the array
[[1. 1. 1.]
 [1. 0. 1.]
 [1. 1. 1.]]


# 9.How to add a border (filled with 0's) around an existing array?

In [9]:
import numpy as np
x = np.ones((3,3))
print("Original array:")
print(x)
print("0 on the border and 1 inside in the array")
x = np.pad(x, pad_width=1, mode='constant', constant_values=0)
print(x)


Original array:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
0 on the border and 1 inside in the array
[[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0.]]


# 10.What is the result of the following expression?

In [10]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1

False

# 11.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [11]:
import numpy as np
x = np.diag([1, 2, 3, 4])
print(x)


[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


# 12.Create a 8x8 matrix and fill it with a checkerboard pattern

In [12]:
import numpy as np
print("Checkerboard pattern:")
x = np.zeros((8,8),dtype=int)
print(x)


Checkerboard pattern:
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0]]


# 13.Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?


In [13]:
print (np.unravel_index(100, (6,7,8)))

(1, 5, 4)


# 14.Create a checkerboard 8x8 matrix using the tile function

In [14]:
array= np.array([[0,1], [1,0]])
x = np.tile(array,(4,4))
print (x)



[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


# 15.Normalize a 5x5 random matrix

In [15]:
Z = np.random.random((5,5))
Zmax, Zmin = Z.max(), Z.min()
Z= (Z-Zmin)/(Zmax-Zmin)
print (Z)


[[0.         0.75691744 1.         0.20491182 0.94231594]
 [0.58464643 0.25134828 0.11820721 0.49949049 0.94564096]
 [0.19088937 0.61859647 0.76360058 0.38724278 0.75768537]
 [0.33122779 0.32027458 0.43189458 0.0228785  0.03020833]
 [0.16008585 0.02087732 0.08635068 0.36127479 0.61094966]]


# 16.Create a custom dtype that describes a color as four unsigned bytes (RGBA)

In [16]:
RGBA = np.dtype([('red',np.ubyte),('green',np.ubyte),('blue',np.ubyte),('alpha',np.ubyte)])
color = np.array((1,2,3,4),dtype = RGBA)
print(color['red'])
print(color['green'])
print(color['blue'])
print(color['alpha'])
type(color)

1
2
3
4


numpy.ndarray

# 17.Multiply a 5x3 matrix by a 3x2 matrix (real matrix product)

In [17]:
arr_1 = np.random.random((5,3))
arr_2 = np.random.random((3,2))
print(arr_1 @ arr_2)
np.dot(arr_1,arr_2)

[[0.43109392 0.93959546]
 [0.349994   0.64150014]
 [0.29147494 0.81071942]
 [0.63223563 1.09424198]
 [0.53629329 1.04073945]]


array([[0.43109392, 0.93959546],
       [0.349994  , 0.64150014],
       [0.29147494, 0.81071942],
       [0.63223563, 1.09424198],
       [0.53629329, 1.04073945]])

# 18.Given a 1D array, negate all elements which are between 3 and 8, in place

In [18]:
arr = np.arange(12)
print(arr>=3)
arr[(arr>=3) & (arr<=8)]*=(-1)
print(arr)

arr = np.arange(12)

[False False False  True  True  True  True  True  True  True  True  True]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11]


# 19.What is the output of the following script?

In [19]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


# 20.Consider an integer vector Z, which of these expressions are legal

In [20]:
Z = arange(10)
Z**Z
Z_2 = 2 << Z >> 2
print([bin(2) for z in Z_2])
print([bin(z) for z in 2 << Z_2])


['0b10', '0b10', '0b10', '0b10', '0b10', '0b10', '0b10', '0b10', '0b10', '0b10']
['0b10', '0b100', '0b1000', '0b100000', '0b1000000000', '0b100000000000000000', '0b0', '0b0', '0b0', '0b0']


# 21.What are the result of the following expressions?

In [21]:
np.array([np.nan]).astype(int).astype(float)

array([-2.14748365e+09])

# 22.How to round away from zero a float array ?

In [22]:
arr = np.random.random((3,3))
print(arr)
arr = np.round(arr,2)
print(arr)

[[0.85484137 0.56749886 0.09333785]
 [0.81090216 0.59845395 0.30434612]
 [0.10848091 0.50771337 0.85563872]]
[[0.85 0.57 0.09]
 [0.81 0.6  0.3 ]
 [0.11 0.51 0.86]]


# 23.How to find common values between two arrays?

In [23]:

x1 = np.random.randint(0,10,10)
x2 = np.random.randint(0,10,10)
print(np.intersect1d(x1,x2))


[1 2 4 6]


# 24.How to get the dates of yesterday, today and tomorrow?

In [24]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
print("Yestraday: ",yesterday)
today     = np.datetime64('today', 'D')
print("Today: ",today)
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
print("Tomorrow: ",tomorrow)

Yestraday:  2021-09-05
Today:  2021-09-06
Tomorrow:  2021-09-07


# 25.How to get all the dates corresponding to the month of July 2016

In [25]:
x = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(x)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


# 26.How to compute ((A+B)*(-A/2)) in place (without copy)?

In [26]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

# 27.Extract the integer part of a random array of positive numbers using 4 different methods

In [27]:
x = np.random.uniform(0,10,10)
print (x - x%1)
print (np.floor(x))
print (np.ceil(x)-1)
print (x.astype(int))

[1. 8. 5. 3. 8. 1. 0. 6. 4. 9.]
[1. 8. 5. 3. 8. 1. 0. 6. 4. 9.]
[1. 8. 5. 3. 8. 1. 0. 6. 4. 9.]
[1 8 5 3 8 1 0 6 4 9]


# 28.Create a 5x5 matrix with row values ranging from 0 to 4

In [28]:
x = np.zeros((5,5))
x += np.arange(5)
print(x)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


# 29.Consider a generator function that generates 10 integers and use it to build an array

In [29]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


# 30.Create a vector of size 10 with values ranging from 0 to 1, both excluded

In [30]:
x = np.linspace(0,1,11,endpoint=False)[1:]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


# 31.Create a random vector of size 10 and sort it

In [31]:
x = np.random.random(10)
x.sort()
print(x)

[0.01112623 0.08495781 0.10869356 0.14839612 0.62483668 0.63958343
 0.68358566 0.70167242 0.8394017  0.9422351 ]


# 32.How to sum a small array faster than np.sum?

In [32]:
x = np.arange(10)
np.add.reduce(x)

45

# 33.Consider two random array A and B, check if they are equal

In [33]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
print(A)
print('*'*20)
print(B)
print('*'*20)

[0 0 1 0 1]
********************
[0 0 1 0 0]
********************


# 34.Make an array immutable (read-only)

In [34]:
import numpy as np
 
a = np.zeros(7)
print("Before any change ")
print(a)
 
a[1] = 2
print("Before after first change ")
print(a)
  

Before any change 
[0. 0. 0. 0. 0. 0. 0.]
Before after first change 
[0. 2. 0. 0. 0. 0. 0.]


# 35.Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates

In [35]:
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[1.19969816 0.54272539 1.00137971 0.93043616 0.60204736 0.86548313
 0.85456389 0.82746035 1.15813119 0.73852324]
[0.94852108 1.30874242 0.09970612 0.91208292 0.86877612 0.59124716
 0.68191458 0.30567047 0.77049408 0.02628205]


# 36.Create random vector of size 10 and replace the maximum value by 0

In [36]:
x = np.random.random(10)
x[x.argmax()] = 0
print(x)

[0.         0.29515429 0.6714423  0.70847007 0.74966135 0.24096109
 0.7774281  0.20240839 0.10379304 0.51584637]


# 37.Create a structured array with x and y coordinates covering the [0,1]x[0,1] area

In [37]:
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


# 38 Print the minimum and maximum representable value for each numpy scalar type

In [38]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


# 39.Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

# 39.Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))

In [39]:
Y = np.random.randint(0,11,10)
X = np.random.randint(11,22,10)
print(Y.reshape(1,10))
Y = np.tile(Y,(10,1))
print(X)
X  = np.tile(X,(10,1)).T
print(X)
C = 1/(X - Y)


[[ 9  0 10  1  2  4  6  2 10  0]]
[18 16 18 14 12 11 18 19 15 18]
[[18 18 18 18 18 18 18 18 18 18]
 [16 16 16 16 16 16 16 16 16 16]
 [18 18 18 18 18 18 18 18 18 18]
 [14 14 14 14 14 14 14 14 14 14]
 [12 12 12 12 12 12 12 12 12 12]
 [11 11 11 11 11 11 11 11 11 11]
 [18 18 18 18 18 18 18 18 18 18]
 [19 19 19 19 19 19 19 19 19 19]
 [15 15 15 15 15 15 15 15 15 15]
 [18 18 18 18 18 18 18 18 18 18]]


# 40 Create a structured array representing a position (x,y) and a color (r,g,b)

In [40]:
import numpy as np
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]
